import { captureJobPostings } from '@haul/payments';
import { percent, shekels } from '@haul/types';
import { sql } from 'drizzle-orm';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { createClient, type Database } from '../client.js';

/**
 * ---------------------------------------------------------------------------
 * Database-level money invariants
 * ---------------------------------------------------------------------------
 * The balance rule is already enforced in the Zod schema and in the posting
 * functions. It is enforced here as well, because both of those live in
 * application code and this does not.
 *
 * A ledger that can be written unbalanced by a migration script, a console
 * session or a future service in another language is not a ledger. These tests
 * prove the database itself refuses.
 * ---------------------------------------------------------------------------
 */

const DATABASE_URL = process.env['DATABASE_URL'] ?? 'postgresql://haul:haul_dev@localhost:5432/haul';

let db: Database;
let close: () => Promise<void>;
let available = false;

beforeAll(async () => {
  try {
    const client = createClient({ connectionString: DATABASE_URL, maxConnections: 2 });
    db = client.db;
    close = () => client.sql.end();
    await db.execute(sql`select 1`);
    available = true;
  } catch {
    available = false;
  }
});

afterEach(async () => {
  if (!available) return;
  await db.execute(sql`delete from ledger_entries where transaction_id like 'test_%'`);
  await db.execute(sql`delete from ledger_transactions where id like 'test_%'`);
});

afterAll(async () => {
  if (available) await close();
});

async function insertTransaction(id: string, entries: Array<[string, number]>) {
  await db.transaction(async (tx) => {
    await tx.execute(sql`
      insert into ledger_transactions (id, kind, idempotency_key, occurred_at, recorded_at)
      values (${id}, 'capture', ${'idem_' + id}, now(), now())
    `);
    let n = 0;
    for (const [account, amount] of entries) {
      n += 1;
      await tx.execute(sql`
        insert into ledger_entries (id, transaction_id, account, amount)
        values (${`${id}_e${n}`}, ${id}, ${sql.raw(`'${account}'`)}::ledger_account, ${amount})
      `);
    }
  });
}

describe.runIf(process.env['SKIP_DB'] !== '1')('the ledger refuses to hold an imbalance', () => {
  it('rejects a transaction whose entries do not sum to zero', async () => {
    if (!available) return;

    await expect(
      insertTransaction('test_bad', [
        ['psp_clearing', shekels(248)],
        ['driver_payable', -shekels(198.4)],
        // Revenue and VAT deliberately missing — ₪49.60 unaccounted for.
      ]),
    ).rejects.toThrow(/does not balance/);
  });

  it('accepts a transaction that balances', async () => {
    if (!available) return;

    await insertTransaction('test_good', [
      ['psp_clearing', shekels(248)],
      ['driver_payable', -shekels(198.4)],
      ['platform_revenue', -shekels(42.03)],
      ['vat_payable', -shekels(7.57)],
    ]);

    const rows = await db.execute<{ total: number }>(sql`
      select coalesce(sum(amount), 0)::int as total
      from ledger_entries where transaction_id = 'test_good'
    `);
    expect((rows as unknown as Array<{ total: number }>)[0]?.total).toBe(0);
  });

  it('accepts what the posting functions actually produce', async () => {
    if (!available) return;

    // The real check: postings generated by @haul/payments must survive the
    // database's own rule. If the two ever disagree, one of them is wrong.
    const tx = captureJobPostings(
      { grossTotal: shekels(248), driverPayout: shekels(198.4), vatRate: percent(18) },
      {
        transactionId: 'test_engine',
        idempotencyKey: 'idem_test_engine',
        occurredAt: new Date(),
        jobId: null as never,
      },
    );

    await expect(
      insertTransaction(
        'test_engine',
        tx.entries.map((e) => [e.account, e.amount] as [string, number]),
      ),
    ).resolves.not.toThrow();
  });

  it('rejects a capture larger than its authorization', async () => {
    if (!available) return;

    // The rule the price lock rests on, made structural rather than hopeful.
    await expect(
      db.execute(sql`
        insert into payment_authorizations
          (id, job_id, customer_id, provider_id, provider_ref, token, amount, captured_amount, expires_at)
        values ('test_auth', null, null, 'fake', 'ref', 'tok', 10000, 20000, now())
      `),
    ).rejects.toThrow();
  });

  it('rejects a job whose window ends before it starts', async () => {
    if (!available) return;
    await expect(
      db.execute(sql`
        insert into jobs (id, reference, city_id, customer_id, vehicle_class_id, crew_size,
                          schedule_kind, window_start, window_end,
                          estimated_working_minutes, routed_distance_meters)
        values ('test_job', 'HL-TEST', 'tel-aviv', null, 'van', 2, 'now',
                now() + interval '2 hours', now(), 120, 5000)
      `),
    ).rejects.toThrow();
  });

  it('rejects a rating outside 1–5', async () => {
    if (!available) return;
    await expect(
      db.execute(sql`
        insert into ratings (id, job_id, subject, stars) values ('test_r', null, 'driver', 7)
      `),
    ).rejects.toThrow();
  });
});
